// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/the-new-day/wiki-earnings/internal/domain/entity"
)

// NewMockEditorReader creates a new instance of MockEditorReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEditorReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEditorReader {
	mock := &MockEditorReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEditorReader is an autogenerated mock type for the EditorReader type
type MockEditorReader struct {
	mock.Mock
}

type MockEditorReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEditorReader) EXPECT() *MockEditorReader_Expecter {
	return &MockEditorReader_Expecter{mock: &_m.Mock}
}

// FindByNickname provides a mock function for the type MockEditorReader
func (_mock *MockEditorReader) FindByNickname(ctx context.Context, nickname string) (entity.Editor, error) {
	ret := _mock.Called(ctx, nickname)

	if len(ret) == 0 {
		panic("no return value specified for FindByNickname")
	}

	var r0 entity.Editor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.Editor, error)); ok {
		return returnFunc(ctx, nickname)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.Editor); ok {
		r0 = returnFunc(ctx, nickname)
	} else {
		r0 = ret.Get(0).(entity.Editor)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, nickname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEditorReader_FindByNickname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNickname'
type MockEditorReader_FindByNickname_Call struct {
	*mock.Call
}

// FindByNickname is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
func (_e *MockEditorReader_Expecter) FindByNickname(ctx any, nickname any) *MockEditorReader_FindByNickname_Call {
	return &MockEditorReader_FindByNickname_Call{Call: _e.mock.On("FindByNickname", ctx, nickname)}
}

func (_c *MockEditorReader_FindByNickname_Call) Run(run func(ctx context.Context, nickname string)) *MockEditorReader_FindByNickname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEditorReader_FindByNickname_Call) Return(editor entity.Editor, err error) *MockEditorReader_FindByNickname_Call {
	_c.Call.Return(editor, err)
	return _c
}

func (_c *MockEditorReader_FindByNickname_Call) RunAndReturn(run func(ctx context.Context, nickname string) (entity.Editor, error)) *MockEditorReader_FindByNickname_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockEditorReader
func (_mock *MockEditorReader) GetByID(ctx context.Context, id int64) (entity.Editor, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entity.Editor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (entity.Editor, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) entity.Editor); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Editor)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEditorReader_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockEditorReader_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockEditorReader_Expecter) GetByID(ctx any, id any) *MockEditorReader_GetByID_Call {
	return &MockEditorReader_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockEditorReader_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockEditorReader_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEditorReader_GetByID_Call) Return(editor entity.Editor, err error) *MockEditorReader_GetByID_Call {
	_c.Call.Return(editor, err)
	return _c
}

func (_c *MockEditorReader_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (entity.Editor, error)) *MockEditorReader_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
