// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/the-new-day/wiki-earnings/internal/domain/entity"
)

// NewMockPaymentCorrectionReader creates a new instance of MockPaymentCorrectionReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentCorrectionReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentCorrectionReader {
	mock := &MockPaymentCorrectionReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentCorrectionReader is an autogenerated mock type for the PaymentCorrectionReader type
type MockPaymentCorrectionReader struct {
	mock.Mock
}

type MockPaymentCorrectionReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentCorrectionReader) EXPECT() *MockPaymentCorrectionReader_Expecter {
	return &MockPaymentCorrectionReader_Expecter{mock: &_m.Mock}
}

// ListByEditor provides a mock function for the type MockPaymentCorrectionReader
func (_mock *MockPaymentCorrectionReader) ListByEditor(ctx context.Context, editorID int64, from time.Time, to time.Time) ([]entity.PaymentCorrection, error) {
	ret := _mock.Called(ctx, editorID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListByEditor")
	}

	var r0 []entity.PaymentCorrection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) ([]entity.PaymentCorrection, error)); ok {
		return returnFunc(ctx, editorID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) []entity.PaymentCorrection); ok {
		r0 = returnFunc(ctx, editorID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PaymentCorrection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, editorID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentCorrectionReader_ListByEditor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByEditor'
type MockPaymentCorrectionReader_ListByEditor_Call struct {
	*mock.Call
}

// ListByEditor is a helper method to define mock.On call
//   - ctx context.Context
//   - editorID int64
//   - from time.Time
//   - to time.Time
func (_e *MockPaymentCorrectionReader_Expecter) ListByEditor(ctx any, editorID any, from any, to any) *MockPaymentCorrectionReader_ListByEditor_Call {
	return &MockPaymentCorrectionReader_ListByEditor_Call{Call: _e.mock.On("ListByEditor", ctx, editorID, from, to)}
}

func (_c *MockPaymentCorrectionReader_ListByEditor_Call) Run(run func(ctx context.Context, editorID int64, from time.Time, to time.Time)) *MockPaymentCorrectionReader_ListByEditor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPaymentCorrectionReader_ListByEditor_Call) Return(paymentCorrections []entity.PaymentCorrection, err error) *MockPaymentCorrectionReader_ListByEditor_Call {
	_c.Call.Return(paymentCorrections, err)
	return _c
}

func (_c *MockPaymentCorrectionReader_ListByEditor_Call) RunAndReturn(run func(ctx context.Context, editorID int64, from time.Time, to time.Time) ([]entity.PaymentCorrection, error)) *MockPaymentCorrectionReader_ListByEditor_Call {
	_c.Call.Return(run)
	return _c
}

// SumByEditor provides a mock function for the type MockPaymentCorrectionReader
func (_mock *MockPaymentCorrectionReader) SumByEditor(ctx context.Context, from time.Time, to time.Time) ([]entity.EditorEarnings, error) {
	ret := _mock.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SumByEditor")
	}

	var r0 []entity.EditorEarnings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]entity.EditorEarnings, error)); ok {
		return returnFunc(ctx, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []entity.EditorEarnings); ok {
		r0 = returnFunc(ctx, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.EditorEarnings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentCorrectionReader_SumByEditor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumByEditor'
type MockPaymentCorrectionReader_SumByEditor_Call struct {
	*mock.Call
}

// SumByEditor is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
func (_e *MockPaymentCorrectionReader_Expecter) SumByEditor(ctx any, from any, to any) *MockPaymentCorrectionReader_SumByEditor_Call {
	return &MockPaymentCorrectionReader_SumByEditor_Call{Call: _e.mock.On("SumByEditor", ctx, from, to)}
}

func (_c *MockPaymentCorrectionReader_SumByEditor_Call) Run(run func(ctx context.Context, from time.Time, to time.Time)) *MockPaymentCorrectionReader_SumByEditor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPaymentCorrectionReader_SumByEditor_Call) Return(editorEarningss []entity.EditorEarnings, err error) *MockPaymentCorrectionReader_SumByEditor_Call {
	_c.Call.Return(editorEarningss, err)
	return _c
}

func (_c *MockPaymentCorrectionReader_SumByEditor_Call) RunAndReturn(run func(ctx context.Context, from time.Time, to time.Time) ([]entity.EditorEarnings, error)) *MockPaymentCorrectionReader_SumByEditor_Call {
	_c.Call.Return(run)
	return _c
}
