// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/the-new-day/wiki-earnings/internal/domain/entity"
)

// NewMockRevisionReader creates a new instance of MockRevisionReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRevisionReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRevisionReader {
	mock := &MockRevisionReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRevisionReader is an autogenerated mock type for the RevisionReader type
type MockRevisionReader struct {
	mock.Mock
}

type MockRevisionReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRevisionReader) EXPECT() *MockRevisionReader_Expecter {
	return &MockRevisionReader_Expecter{mock: &_m.Mock}
}

// ListByEditor provides a mock function for the type MockRevisionReader
func (_mock *MockRevisionReader) ListByEditor(ctx context.Context, editorID int64, from time.Time, to time.Time) ([]entity.Revision, error) {
	ret := _mock.Called(ctx, editorID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListByEditor")
	}

	var r0 []entity.Revision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) ([]entity.Revision, error)); ok {
		return returnFunc(ctx, editorID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) []entity.Revision); ok {
		r0 = returnFunc(ctx, editorID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Revision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, editorID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRevisionReader_ListByEditor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByEditor'
type MockRevisionReader_ListByEditor_Call struct {
	*mock.Call
}

// ListByEditor is a helper method to define mock.On call
//   - ctx context.Context
//   - editorID int64
//   - from time.Time
//   - to time.Time
func (_e *MockRevisionReader_Expecter) ListByEditor(ctx any, editorID any, from any, to any) *MockRevisionReader_ListByEditor_Call {
	return &MockRevisionReader_ListByEditor_Call{Call: _e.mock.On("ListByEditor", ctx, editorID, from, to)}
}

func (_c *MockRevisionReader_ListByEditor_Call) Run(run func(ctx context.Context, editorID int64, from time.Time, to time.Time)) *MockRevisionReader_ListByEditor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRevisionReader_ListByEditor_Call) Return(revisions []entity.Revision, err error) *MockRevisionReader_ListByEditor_Call {
	_c.Call.Return(revisions, err)
	return _c
}

func (_c *MockRevisionReader_ListByEditor_Call) RunAndReturn(run func(ctx context.Context, editorID int64, from time.Time, to time.Time) ([]entity.Revision, error)) *MockRevisionReader_ListByEditor_Call {
	_c.Call.Return(run)
	return _c
}

// SumCostByEditor provides a mock function for the type MockRevisionReader
func (_mock *MockRevisionReader) SumCostByEditor(ctx context.Context, from time.Time, to time.Time) ([]entity.EditorEarnings, error) {
	ret := _mock.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SumCostByEditor")
	}

	var r0 []entity.EditorEarnings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]entity.EditorEarnings, error)); ok {
		return returnFunc(ctx, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []entity.EditorEarnings); ok {
		r0 = returnFunc(ctx, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.EditorEarnings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRevisionReader_SumCostByEditor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumCostByEditor'
type MockRevisionReader_SumCostByEditor_Call struct {
	*mock.Call
}

// SumCostByEditor is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
func (_e *MockRevisionReader_Expecter) SumCostByEditor(ctx any, from any, to any) *MockRevisionReader_SumCostByEditor_Call {
	return &MockRevisionReader_SumCostByEditor_Call{Call: _e.mock.On("SumCostByEditor", ctx, from, to)}
}

func (_c *MockRevisionReader_SumCostByEditor_Call) Run(run func(ctx context.Context, from time.Time, to time.Time)) *MockRevisionReader_SumCostByEditor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRevisionReader_SumCostByEditor_Call) Return(editorEarningss []entity.EditorEarnings, err error) *MockRevisionReader_SumCostByEditor_Call {
	_c.Call.Return(editorEarningss, err)
	return _c
}

func (_c *MockRevisionReader_SumCostByEditor_Call) RunAndReturn(run func(ctx context.Context, from time.Time, to time.Time) ([]entity.EditorEarnings, error)) *MockRevisionReader_SumCostByEditor_Call {
	_c.Call.Return(run)
	return _c
}

// SumCostForEditor provides a mock function for the type MockRevisionReader
func (_mock *MockRevisionReader) SumCostForEditor(ctx context.Context, editorID int64, from time.Time, to time.Time) (int64, error) {
	ret := _mock.Called(ctx, editorID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SumCostForEditor")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) (int64, error)); ok {
		return returnFunc(ctx, editorID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) int64); ok {
		r0 = returnFunc(ctx, editorID, from, to)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, editorID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRevisionReader_SumCostForEditor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumCostForEditor'
type MockRevisionReader_SumCostForEditor_Call struct {
	*mock.Call
}

// SumCostForEditor is a helper method to define mock.On call
//   - ctx context.Context
//   - editorID int64
//   - from time.Time
//   - to time.Time
func (_e *MockRevisionReader_Expecter) SumCostForEditor(ctx any, editorID any, from any, to any) *MockRevisionReader_SumCostForEditor_Call {
	return &MockRevisionReader_SumCostForEditor_Call{Call: _e.mock.On("SumCostForEditor", ctx, editorID, from, to)}
}

func (_c *MockRevisionReader_SumCostForEditor_Call) Run(run func(ctx context.Context, editorID int64, from time.Time, to time.Time)) *MockRevisionReader_SumCostForEditor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRevisionReader_SumCostForEditor_Call) Return(n int64, err error) *MockRevisionReader_SumCostForEditor_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRevisionReader_SumCostForEditor_Call) RunAndReturn(run func(ctx context.Context, editorID int64, from time.Time, to time.Time) (int64, error)) *MockRevisionReader_SumCostForEditor_Call {
	_c.Call.Return(run)
	return _c
}
