// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSyncer creates a new instance of MockSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncer {
	mock := &MockSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSyncer is an autogenerated mock type for the Syncer type
type MockSyncer struct {
	mock.Mock
}

type MockSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncer) EXPECT() *MockSyncer_Expecter {
	return &MockSyncer_Expecter{mock: &_m.Mock}
}

// Sync provides a mock function for the type MockSyncer
func (_mock *MockSyncer) Sync(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncer_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockSyncer_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSyncer_Expecter) Sync(ctx any) *MockSyncer_Sync_Call {
	return &MockSyncer_Sync_Call{Call: _e.mock.On("Sync", ctx)}
}

func (_c *MockSyncer_Sync_Call) Run(run func(ctx context.Context)) *MockSyncer_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSyncer_Sync_Call) Return(err error) *MockSyncer_Sync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncer_Sync_Call) RunAndReturn(run func(ctx context.Context) error) *MockSyncer_Sync_Call {
	_c.Call.Return(run)
	return _c
}
