// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/the-new-day/wiki-earnings/internal/domain/entity"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// FindByNickname provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByNickname(ctx context.Context, nickname string) (entity.Editor, error) {
	ret := _mock.Called(ctx, nickname)

	if len(ret) == 0 {
		panic("no return value specified for FindByNickname")
	}

	var r0 entity.Editor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.Editor, error)); ok {
		return returnFunc(ctx, nickname)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.Editor); ok {
		r0 = returnFunc(ctx, nickname)
	} else {
		r0 = ret.Get(0).(entity.Editor)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, nickname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByNickname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNickname'
type MockRepository_FindByNickname_Call struct {
	*mock.Call
}

// FindByNickname is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
func (_e *MockRepository_Expecter) FindByNickname(ctx any, nickname any) *MockRepository_FindByNickname_Call {
	return &MockRepository_FindByNickname_Call{Call: _e.mock.On("FindByNickname", ctx, nickname)}
}

func (_c *MockRepository_FindByNickname_Call) Run(run func(ctx context.Context, nickname string)) *MockRepository_FindByNickname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByNickname_Call) Return(editor entity.Editor, err error) *MockRepository_FindByNickname_Call {
	_c.Call.Return(editor, err)
	return _c
}

func (_c *MockRepository_FindByNickname_Call) RunAndReturn(run func(ctx context.Context, nickname string) (entity.Editor, error)) *MockRepository_FindByNickname_Call {
	_c.Call.Return(run)
	return _c
}

// SetPaymentsNickname provides a mock function for the type MockRepository
func (_mock *MockRepository) SetPaymentsNickname(ctx context.Context, editorID int64, nickname string) error {
	ret := _mock.Called(ctx, editorID, nickname)

	if len(ret) == 0 {
		panic("no return value specified for SetPaymentsNickname")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, editorID, nickname)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetPaymentsNickname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPaymentsNickname'
type MockRepository_SetPaymentsNickname_Call struct {
	*mock.Call
}

// SetPaymentsNickname is a helper method to define mock.On call
//   - ctx context.Context
//   - editorID int64
//   - nickname string
func (_e *MockRepository_Expecter) SetPaymentsNickname(ctx any, editorID any, nickname any) *MockRepository_SetPaymentsNickname_Call {
	return &MockRepository_SetPaymentsNickname_Call{Call: _e.mock.On("SetPaymentsNickname", ctx, editorID, nickname)}
}

func (_c *MockRepository_SetPaymentsNickname_Call) Run(run func(ctx context.Context, editorID int64, nickname string)) *MockRepository_SetPaymentsNickname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SetPaymentsNickname_Call) Return(err error) *MockRepository_SetPaymentsNickname_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetPaymentsNickname_Call) RunAndReturn(run func(ctx context.Context, editorID int64, nickname string) error) *MockRepository_SetPaymentsNickname_Call {
	_c.Call.Return(run)
	return _c
}
