// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskPoster creates a new instance of MockTaskPoster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskPoster(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskPoster {
	mock := &MockTaskPoster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskPoster is an autogenerated mock type for the TaskPoster type
type MockTaskPoster struct {
	mock.Mock
}

type MockTaskPoster_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskPoster) EXPECT() *MockTaskPoster_Expecter {
	return &MockTaskPoster_Expecter{mock: &_m.Mock}
}

// PostTask provides a mock function for the type MockTaskPoster
func (_mock *MockTaskPoster) PostTask(ctx context.Context, localizedTexts map[string]string) error {
	ret := _mock.Called(ctx, localizedTexts)

	if len(ret) == 0 {
		panic("no return value specified for PostTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) error); ok {
		r0 = returnFunc(ctx, localizedTexts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskPoster_PostTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostTask'
type MockTaskPoster_PostTask_Call struct {
	*mock.Call
}

// PostTask is a helper method to define mock.On call
//   - ctx context.Context
//   - localizedTexts map[string]string
func (_e *MockTaskPoster_Expecter) PostTask(ctx any, localizedTexts any) *MockTaskPoster_PostTask_Call {
	return &MockTaskPoster_PostTask_Call{Call: _e.mock.On("PostTask", ctx, localizedTexts)}
}

func (_c *MockTaskPoster_PostTask_Call) Run(run func(ctx context.Context, localizedTexts map[string]string)) *MockTaskPoster_PostTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskPoster_PostTask_Call) Return(err error) *MockTaskPoster_PostTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskPoster_PostTask_Call) RunAndReturn(run func(ctx context.Context, localizedTexts map[string]string) error) *MockTaskPoster_PostTask_Call {
	_c.Call.Return(run)
	return _c
}
