// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/the-new-day/wiki-earnings/internal/domain/entity"
)

// NewMockTranslator creates a new instance of MockTranslator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranslator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranslator {
	mock := &MockTranslator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTranslator is an autogenerated mock type for the Translator type
type MockTranslator struct {
	mock.Mock
}

type MockTranslator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranslator) EXPECT() *MockTranslator_Expecter {
	return &MockTranslator_Expecter{mock: &_m.Mock}
}

// Translate provides a mock function for the type MockTranslator
func (_mock *MockTranslator) Translate(ctx context.Context, text string, sourceLang entity.Language, targetLang entity.Language) (string, error) {
	ret := _mock.Called(ctx, text, sourceLang, targetLang)

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.Language, entity.Language) (string, error)); ok {
		return returnFunc(ctx, text, sourceLang, targetLang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.Language, entity.Language) string); ok {
		r0 = returnFunc(ctx, text, sourceLang, targetLang)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, entity.Language, entity.Language) error); ok {
		r1 = returnFunc(ctx, text, sourceLang, targetLang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranslator_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type MockTranslator_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - sourceLang entity.Language
//   - targetLang entity.Language
func (_e *MockTranslator_Expecter) Translate(ctx any, text any, sourceLang any, targetLang any) *MockTranslator_Translate_Call {
	return &MockTranslator_Translate_Call{Call: _e.mock.On("Translate", ctx, text, sourceLang, targetLang)}
}

func (_c *MockTranslator_Translate_Call) Run(run func(ctx context.Context, text string, sourceLang entity.Language, targetLang entity.Language)) *MockTranslator_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entity.Language
		if args[2] != nil {
			arg2 = args[2].(entity.Language)
		}
		var arg3 entity.Language
		if args[3] != nil {
			arg3 = args[3].(entity.Language)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTranslator_Translate_Call) Return(s string, err error) *MockTranslator_Translate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTranslator_Translate_Call) RunAndReturn(run func(ctx context.Context, text string, sourceLang entity.Language, targetLang entity.Language) (string, error)) *MockTranslator_Translate_Call {
	_c.Call.Return(run)
	return _c
}
