// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/the-new-day/protanki-wiki-admin/internal/domain/entity"
)

// NewMockDeadLetter creates a new instance of MockDeadLetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeadLetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeadLetter {
	mock := &MockDeadLetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeadLetter is an autogenerated mock type for the DeadLetter type
type MockDeadLetter struct {
	mock.Mock
}

type MockDeadLetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeadLetter) EXPECT() *MockDeadLetter_Expecter {
	return &MockDeadLetter_Expecter{mock: &_m.Mock}
}

// Fail provides a mock function for the type MockDeadLetter
func (_mock *MockDeadLetter) Fail(ctx context.Context, locale string, revID int64, reason string) error {
	ret := _mock.Called(ctx, locale, revID, reason)

	if len(ret) == 0 {
		panic("no return value specified for Fail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string) error); ok {
		r0 = returnFunc(ctx, locale, revID, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeadLetter_Fail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fail'
type MockDeadLetter_Fail_Call struct {
	*mock.Call
}

// Fail is a helper method to define mock.On call
//   - ctx context.Context
//   - locale string
//   - revID int64
//   - reason string
func (_e *MockDeadLetter_Expecter) Fail(ctx any, locale any, revID any, reason any) *MockDeadLetter_Fail_Call {
	return &MockDeadLetter_Fail_Call{Call: _e.mock.On("Fail", ctx, locale, revID, reason)}
}

func (_c *MockDeadLetter_Fail_Call) Run(run func(ctx context.Context, locale string, revID int64, reason string)) *MockDeadLetter_Fail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDeadLetter_Fail_Call) Return(err error) *MockDeadLetter_Fail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeadLetter_Fail_Call) RunAndReturn(run func(ctx context.Context, locale string, revID int64, reason string) error) *MockDeadLetter_Fail_Call {
	_c.Call.Return(run)
	return _c
}

// ListPending provides a mock function for the type MockDeadLetter
func (_mock *MockDeadLetter) ListPending(ctx context.Context, limit int) ([]entity.FailedRevision, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPending")
	}

	var r0 []entity.FailedRevision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]entity.FailedRevision, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []entity.FailedRevision); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.FailedRevision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeadLetter_ListPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPending'
type MockDeadLetter_ListPending_Call struct {
	*mock.Call
}

// ListPending is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockDeadLetter_Expecter) ListPending(ctx any, limit any) *MockDeadLetter_ListPending_Call {
	return &MockDeadLetter_ListPending_Call{Call: _e.mock.On("ListPending", ctx, limit)}
}

func (_c *MockDeadLetter_ListPending_Call) Run(run func(ctx context.Context, limit int)) *MockDeadLetter_ListPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeadLetter_ListPending_Call) Return(failedRevisions []entity.FailedRevision, err error) *MockDeadLetter_ListPending_Call {
	_c.Call.Return(failedRevisions, err)
	return _c
}

func (_c *MockDeadLetter_ListPending_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]entity.FailedRevision, error)) *MockDeadLetter_ListPending_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockDeadLetter
func (_mock *MockDeadLetter) Put(ctx context.Context, f entity.FailedRevision) error {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.FailedRevision) error); ok {
		r0 = returnFunc(ctx, f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeadLetter_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockDeadLetter_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - f entity.FailedRevision
func (_e *MockDeadLetter_Expecter) Put(ctx any, f any) *MockDeadLetter_Put_Call {
	return &MockDeadLetter_Put_Call{Call: _e.mock.On("Put", ctx, f)}
}

func (_c *MockDeadLetter_Put_Call) Run(run func(ctx context.Context, f entity.FailedRevision)) *MockDeadLetter_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.FailedRevision
		if args[1] != nil {
			arg1 = args[1].(entity.FailedRevision)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeadLetter_Put_Call) Return(err error) *MockDeadLetter_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeadLetter_Put_Call) RunAndReturn(run func(ctx context.Context, f entity.FailedRevision) error) *MockDeadLetter_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function for the type MockDeadLetter
func (_mock *MockDeadLetter) Resolve(ctx context.Context, locale string, revID int64) error {
	ret := _mock.Called(ctx, locale, revID)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, locale, revID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeadLetter_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockDeadLetter_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - locale string
//   - revID int64
func (_e *MockDeadLetter_Expecter) Resolve(ctx any, locale any, revID any) *MockDeadLetter_Resolve_Call {
	return &MockDeadLetter_Resolve_Call{Call: _e.mock.On("Resolve", ctx, locale, revID)}
}

func (_c *MockDeadLetter_Resolve_Call) Run(run func(ctx context.Context, locale string, revID int64)) *MockDeadLetter_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeadLetter_Resolve_Call) Return(err error) *MockDeadLetter_Resolve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeadLetter_Resolve_Call) RunAndReturn(run func(ctx context.Context, locale string, revID int64) error) *MockDeadLetter_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// Retire provides a mock function for the type MockDeadLetter
func (_mock *MockDeadLetter) Retire(ctx context.Context, locale string, revID int64, reason string) error {
	ret := _mock.Called(ctx, locale, revID, reason)

	if len(ret) == 0 {
		panic("no return value specified for Retire")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string) error); ok {
		r0 = returnFunc(ctx, locale, revID, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeadLetter_Retire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retire'
type MockDeadLetter_Retire_Call struct {
	*mock.Call
}

// Retire is a helper method to define mock.On call
//   - ctx context.Context
//   - locale string
//   - revID int64
//   - reason string
func (_e *MockDeadLetter_Expecter) Retire(ctx any, locale any, revID any, reason any) *MockDeadLetter_Retire_Call {
	return &MockDeadLetter_Retire_Call{Call: _e.mock.On("Retire", ctx, locale, revID, reason)}
}

func (_c *MockDeadLetter_Retire_Call) Run(run func(ctx context.Context, locale string, revID int64, reason string)) *MockDeadLetter_Retire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDeadLetter_Retire_Call) Return(err error) *MockDeadLetter_Retire_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeadLetter_Retire_Call) RunAndReturn(run func(ctx context.Context, locale string, revID int64, reason string) error) *MockDeadLetter_Retire_Call {
	_c.Call.Return(run)
	return _c
}
