// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/the-new-day/wiki-earnings/internal/domain/entity"
)

// NewMockEditorRegistry creates a new instance of MockEditorRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEditorRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEditorRegistry {
	mock := &MockEditorRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEditorRegistry is an autogenerated mock type for the EditorRegistry type
type MockEditorRegistry struct {
	mock.Mock
}

type MockEditorRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEditorRegistry) EXPECT() *MockEditorRegistry_Expecter {
	return &MockEditorRegistry_Expecter{mock: &_m.Mock}
}

// FindByLocaleUser provides a mock function for the type MockEditorRegistry
func (_mock *MockEditorRegistry) FindByLocaleUser(ctx context.Context, locale string, wikiUserID int64) (entity.Editor, bool, error) {
	ret := _mock.Called(ctx, locale, wikiUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindByLocaleUser")
	}

	var r0 entity.Editor
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (entity.Editor, bool, error)); ok {
		return returnFunc(ctx, locale, wikiUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) entity.Editor); ok {
		r0 = returnFunc(ctx, locale, wikiUserID)
	} else {
		r0 = ret.Get(0).(entity.Editor)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) bool); ok {
		r1 = returnFunc(ctx, locale, wikiUserID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int64) error); ok {
		r2 = returnFunc(ctx, locale, wikiUserID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockEditorRegistry_FindByLocaleUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLocaleUser'
type MockEditorRegistry_FindByLocaleUser_Call struct {
	*mock.Call
}

// FindByLocaleUser is a helper method to define mock.On call
//   - ctx context.Context
//   - locale string
//   - wikiUserID int64
func (_e *MockEditorRegistry_Expecter) FindByLocaleUser(ctx any, locale any, wikiUserID any) *MockEditorRegistry_FindByLocaleUser_Call {
	return &MockEditorRegistry_FindByLocaleUser_Call{Call: _e.mock.On("FindByLocaleUser", ctx, locale, wikiUserID)}
}

func (_c *MockEditorRegistry_FindByLocaleUser_Call) Run(run func(ctx context.Context, locale string, wikiUserID int64)) *MockEditorRegistry_FindByLocaleUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEditorRegistry_FindByLocaleUser_Call) Return(editor entity.Editor, found bool, err error) *MockEditorRegistry_FindByLocaleUser_Call {
	_c.Call.Return(editor, found, err)
	return _c
}

func (_c *MockEditorRegistry_FindByLocaleUser_Call) RunAndReturn(run func(ctx context.Context, locale string, wikiUserID int64) (entity.Editor, bool, error)) *MockEditorRegistry_FindByLocaleUser_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockEditorRegistry
func (_mock *MockEditorRegistry) Register(ctx context.Context, locale string, wikiUserID int64, nickname string) (entity.Editor, error) {
	ret := _mock.Called(ctx, locale, wikiUserID, nickname)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 entity.Editor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string) (entity.Editor, error)); ok {
		return returnFunc(ctx, locale, wikiUserID, nickname)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string) entity.Editor); ok {
		r0 = returnFunc(ctx, locale, wikiUserID, nickname)
	} else {
		r0 = ret.Get(0).(entity.Editor)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, string) error); ok {
		r1 = returnFunc(ctx, locale, wikiUserID, nickname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEditorRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockEditorRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - locale string
//   - wikiUserID int64
//   - nickname string
func (_e *MockEditorRegistry_Expecter) Register(ctx any, locale any, wikiUserID any, nickname any) *MockEditorRegistry_Register_Call {
	return &MockEditorRegistry_Register_Call{Call: _e.mock.On("Register", ctx, locale, wikiUserID, nickname)}
}

func (_c *MockEditorRegistry_Register_Call) Run(run func(ctx context.Context, locale string, wikiUserID int64, nickname string)) *MockEditorRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEditorRegistry_Register_Call) Return(editor entity.Editor, err error) *MockEditorRegistry_Register_Call {
	_c.Call.Return(editor, err)
	return _c
}

func (_c *MockEditorRegistry_Register_Call) RunAndReturn(run func(ctx context.Context, locale string, wikiUserID int64, nickname string) (entity.Editor, error)) *MockEditorRegistry_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockEditorRegistry
func (_mock *MockEditorRegistry) Rename(ctx context.Context, editorID int64, nickname string) error {
	ret := _mock.Called(ctx, editorID, nickname)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, editorID, nickname)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEditorRegistry_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockEditorRegistry_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - ctx context.Context
//   - editorID int64
//   - nickname string
func (_e *MockEditorRegistry_Expecter) Rename(ctx any, editorID any, nickname any) *MockEditorRegistry_Rename_Call {
	return &MockEditorRegistry_Rename_Call{Call: _e.mock.On("Rename", ctx, editorID, nickname)}
}

func (_c *MockEditorRegistry_Rename_Call) Run(run func(ctx context.Context, editorID int64, nickname string)) *MockEditorRegistry_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEditorRegistry_Rename_Call) Return(err error) *MockEditorRegistry_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEditorRegistry_Rename_Call) RunAndReturn(run func(ctx context.Context, editorID int64, nickname string) error) *MockEditorRegistry_Rename_Call {
	_c.Call.Return(run)
	return _c
}
