// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/the-new-day/wiki-earnings/internal/domain/entity"
)

// NewMockPricer creates a new instance of MockPricer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPricer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPricer {
	mock := &MockPricer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPricer is an autogenerated mock type for the Pricer type
type MockPricer struct {
	mock.Mock
}

type MockPricer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPricer) EXPECT() *MockPricer_Expecter {
	return &MockPricer_Expecter{mock: &_m.Mock}
}

// Cost provides a mock function for the type MockPricer
func (_mock *MockPricer) Cost(t entity.RevisionType, prev *entity.ArticleInfo, curr *entity.ArticleInfo) int64 {
	ret := _mock.Called(t, prev, curr)

	if len(ret) == 0 {
		panic("no return value specified for Cost")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(entity.RevisionType, *entity.ArticleInfo, *entity.ArticleInfo) int64); ok {
		r0 = returnFunc(t, prev, curr)
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockPricer_Cost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cost'
type MockPricer_Cost_Call struct {
	*mock.Call
}

// Cost is a helper method to define mock.On call
//   - t entity.RevisionType
//   - prev *entity.ArticleInfo
//   - curr *entity.ArticleInfo
func (_e *MockPricer_Expecter) Cost(t any, prev any, curr any) *MockPricer_Cost_Call {
	return &MockPricer_Cost_Call{Call: _e.mock.On("Cost", t, prev, curr)}
}

func (_c *MockPricer_Cost_Call) Run(run func(t entity.RevisionType, prev *entity.ArticleInfo, curr *entity.ArticleInfo)) *MockPricer_Cost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entity.RevisionType
		if args[0] != nil {
			arg0 = args[0].(entity.RevisionType)
		}
		var arg1 *entity.ArticleInfo
		if args[1] != nil {
			arg1 = args[1].(*entity.ArticleInfo)
		}
		var arg2 *entity.ArticleInfo
		if args[2] != nil {
			arg2 = args[2].(*entity.ArticleInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPricer_Cost_Call) Return(n int64) *MockPricer_Cost_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockPricer_Cost_Call) RunAndReturn(run func(t entity.RevisionType, prev *entity.ArticleInfo, curr *entity.ArticleInfo) int64) *MockPricer_Cost_Call {
	_c.Call.Return(run)
	return _c
}
