// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/the-new-day/wiki-earnings/internal/domain/entity"
)

// NewMockRevisionWriter creates a new instance of MockRevisionWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRevisionWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRevisionWriter {
	mock := &MockRevisionWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRevisionWriter is an autogenerated mock type for the RevisionWriter type
type MockRevisionWriter struct {
	mock.Mock
}

type MockRevisionWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRevisionWriter) EXPECT() *MockRevisionWriter_Expecter {
	return &MockRevisionWriter_Expecter{mock: &_m.Mock}
}

// Upsert provides a mock function for the type MockRevisionWriter
func (_mock *MockRevisionWriter) Upsert(ctx context.Context, r entity.Revision) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Revision) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRevisionWriter_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockRevisionWriter_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - r entity.Revision
func (_e *MockRevisionWriter_Expecter) Upsert(ctx any, r any) *MockRevisionWriter_Upsert_Call {
	return &MockRevisionWriter_Upsert_Call{Call: _e.mock.On("Upsert", ctx, r)}
}

func (_c *MockRevisionWriter_Upsert_Call) Run(run func(ctx context.Context, r entity.Revision)) *MockRevisionWriter_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Revision
		if args[1] != nil {
			arg1 = args[1].(entity.Revision)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRevisionWriter_Upsert_Call) Return(err error) *MockRevisionWriter_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRevisionWriter_Upsert_Call) RunAndReturn(run func(ctx context.Context, r entity.Revision) error) *MockRevisionWriter_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
