// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/the-new-day/wiki-earnings/internal/domain/entity"
)

// NewMockStateStore creates a new instance of MockStateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateStore {
	mock := &MockStateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStateStore is an autogenerated mock type for the StateStore type
type MockStateStore struct {
	mock.Mock
}

type MockStateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateStore) EXPECT() *MockStateStore_Expecter {
	return &MockStateStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockStateStore
func (_mock *MockStateStore) Get(ctx context.Context, locale string) (entity.SyncState, error) {
	ret := _mock.Called(ctx, locale)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.SyncState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.SyncState, error)); ok {
		return returnFunc(ctx, locale)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.SyncState); ok {
		r0 = returnFunc(ctx, locale)
	} else {
		r0 = ret.Get(0).(entity.SyncState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, locale)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStateStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStateStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - locale string
func (_e *MockStateStore_Expecter) Get(ctx any, locale any) *MockStateStore_Get_Call {
	return &MockStateStore_Get_Call{Call: _e.mock.On("Get", ctx, locale)}
}

func (_c *MockStateStore_Get_Call) Run(run func(ctx context.Context, locale string)) *MockStateStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStateStore_Get_Call) Return(syncState entity.SyncState, err error) *MockStateStore_Get_Call {
	_c.Call.Return(syncState, err)
	return _c
}

func (_c *MockStateStore_Get_Call) RunAndReturn(run func(ctx context.Context, locale string) (entity.SyncState, error)) *MockStateStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockStateStore
func (_mock *MockStateStore) Save(ctx context.Context, s entity.SyncState) error {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.SyncState) error); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStateStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStateStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - s entity.SyncState
func (_e *MockStateStore_Expecter) Save(ctx any, s any) *MockStateStore_Save_Call {
	return &MockStateStore_Save_Call{Call: _e.mock.On("Save", ctx, s)}
}

func (_c *MockStateStore_Save_Call) Run(run func(ctx context.Context, s entity.SyncState)) *MockStateStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.SyncState
		if args[1] != nil {
			arg1 = args[1].(entity.SyncState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStateStore_Save_Call) Return(err error) *MockStateStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStateStore_Save_Call) RunAndReturn(run func(ctx context.Context, s entity.SyncState) error) *MockStateStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
