// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/the-new-day/protanki-wiki-admin/internal/domain/entity"
)

// NewMockWikiClient creates a new instance of MockWikiClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWikiClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWikiClient {
	mock := &MockWikiClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWikiClient is an autogenerated mock type for the WikiClient type
type MockWikiClient struct {
	mock.Mock
}

type MockWikiClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWikiClient) EXPECT() *MockWikiClient_Expecter {
	return &MockWikiClient_Expecter{mock: &_m.Mock}
}

// FetchEdit provides a mock function for the type MockWikiClient
func (_mock *MockWikiClient) FetchEdit(ctx context.Context, title string, revID int64, locale string) (entity.Edit, error) {
	ret := _mock.Called(ctx, title, revID, locale)

	if len(ret) == 0 {
		panic("no return value specified for FetchEdit")
	}

	var r0 entity.Edit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string) (entity.Edit, error)); ok {
		return returnFunc(ctx, title, revID, locale)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string) entity.Edit); ok {
		r0 = returnFunc(ctx, title, revID, locale)
	} else {
		r0 = ret.Get(0).(entity.Edit)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, string) error); ok {
		r1 = returnFunc(ctx, title, revID, locale)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWikiClient_FetchEdit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchEdit'
type MockWikiClient_FetchEdit_Call struct {
	*mock.Call
}

// FetchEdit is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - revID int64
//   - locale string
func (_e *MockWikiClient_Expecter) FetchEdit(ctx any, title any, revID any, locale any) *MockWikiClient_FetchEdit_Call {
	return &MockWikiClient_FetchEdit_Call{Call: _e.mock.On("FetchEdit", ctx, title, revID, locale)}
}

func (_c *MockWikiClient_FetchEdit_Call) Run(run func(ctx context.Context, title string, revID int64, locale string)) *MockWikiClient_FetchEdit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWikiClient_FetchEdit_Call) Return(edit entity.Edit, err error) *MockWikiClient_FetchEdit_Call {
	_c.Call.Return(edit, err)
	return _c
}

func (_c *MockWikiClient_FetchEdit_Call) RunAndReturn(run func(ctx context.Context, title string, revID int64, locale string) (entity.Edit, error)) *MockWikiClient_FetchEdit_Call {
	_c.Call.Return(run)
	return _c
}

// FetchRecentChanges provides a mock function for the type MockWikiClient
func (_mock *MockWikiClient) FetchRecentChanges(ctx context.Context, locale string, since time.Time, limit int) ([]entity.RecentChange, error) {
	ret := _mock.Called(ctx, locale, since, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchRecentChanges")
	}

	var r0 []entity.RecentChange
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, int) ([]entity.RecentChange, error)); ok {
		return returnFunc(ctx, locale, since, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, int) []entity.RecentChange); ok {
		r0 = returnFunc(ctx, locale, since, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.RecentChange)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, int) error); ok {
		r1 = returnFunc(ctx, locale, since, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWikiClient_FetchRecentChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRecentChanges'
type MockWikiClient_FetchRecentChanges_Call struct {
	*mock.Call
}

// FetchRecentChanges is a helper method to define mock.On call
//   - ctx context.Context
//   - locale string
//   - since time.Time
//   - limit int
func (_e *MockWikiClient_Expecter) FetchRecentChanges(ctx any, locale any, since any, limit any) *MockWikiClient_FetchRecentChanges_Call {
	return &MockWikiClient_FetchRecentChanges_Call{Call: _e.mock.On("FetchRecentChanges", ctx, locale, since, limit)}
}

func (_c *MockWikiClient_FetchRecentChanges_Call) Run(run func(ctx context.Context, locale string, since time.Time, limit int)) *MockWikiClient_FetchRecentChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWikiClient_FetchRecentChanges_Call) Return(recentChanges []entity.RecentChange, err error) *MockWikiClient_FetchRecentChanges_Call {
	_c.Call.Return(recentChanges, err)
	return _c
}

func (_c *MockWikiClient_FetchRecentChanges_Call) RunAndReturn(run func(ctx context.Context, locale string, since time.Time, limit int) ([]entity.RecentChange, error)) *MockWikiClient_FetchRecentChanges_Call {
	_c.Call.Return(run)
	return _c
}
