// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/the-new-day/wiki-earnings/internal/domain/entity"
)

// NewMockRevisionStore creates a new instance of MockRevisionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRevisionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRevisionStore {
	mock := &MockRevisionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRevisionStore is an autogenerated mock type for the RevisionStore type
type MockRevisionStore struct {
	mock.Mock
}

type MockRevisionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRevisionStore) EXPECT() *MockRevisionStore_Expecter {
	return &MockRevisionStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockRevisionStore
func (_mock *MockRevisionStore) Get(ctx context.Context, locale string, revisionID int64) (entity.Revision, error) {
	ret := _mock.Called(ctx, locale, revisionID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Revision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (entity.Revision, error)); ok {
		return returnFunc(ctx, locale, revisionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) entity.Revision); ok {
		r0 = returnFunc(ctx, locale, revisionID)
	} else {
		r0 = ret.Get(0).(entity.Revision)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, locale, revisionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRevisionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRevisionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - locale string
//   - revisionID int64
func (_e *MockRevisionStore_Expecter) Get(ctx any, locale any, revisionID any) *MockRevisionStore_Get_Call {
	return &MockRevisionStore_Get_Call{Call: _e.mock.On("Get", ctx, locale, revisionID)}
}

func (_c *MockRevisionStore_Get_Call) Run(run func(ctx context.Context, locale string, revisionID int64)) *MockRevisionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRevisionStore_Get_Call) Return(revision entity.Revision, err error) *MockRevisionStore_Get_Call {
	_c.Call.Return(revision, err)
	return _c
}

func (_c *MockRevisionStore_Get_Call) RunAndReturn(run func(ctx context.Context, locale string, revisionID int64) (entity.Revision, error)) *MockRevisionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// OverrideCost provides a mock function for the type MockRevisionStore
func (_mock *MockRevisionStore) OverrideCost(ctx context.Context, locale string, revisionID int64, newCost int64, changedBy string) (entity.Revision, error) {
	ret := _mock.Called(ctx, locale, revisionID, newCost, changedBy)

	if len(ret) == 0 {
		panic("no return value specified for OverrideCost")
	}

	var r0 entity.Revision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) (entity.Revision, error)); ok {
		return returnFunc(ctx, locale, revisionID, newCost, changedBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) entity.Revision); ok {
		r0 = returnFunc(ctx, locale, revisionID, newCost, changedBy)
	} else {
		r0 = ret.Get(0).(entity.Revision)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64, string) error); ok {
		r1 = returnFunc(ctx, locale, revisionID, newCost, changedBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRevisionStore_OverrideCost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OverrideCost'
type MockRevisionStore_OverrideCost_Call struct {
	*mock.Call
}

// OverrideCost is a helper method to define mock.On call
//   - ctx context.Context
//   - locale string
//   - revisionID int64
//   - newCost int64
//   - changedBy string
func (_e *MockRevisionStore_Expecter) OverrideCost(ctx any, locale any, revisionID any, newCost any, changedBy any) *MockRevisionStore_OverrideCost_Call {
	return &MockRevisionStore_OverrideCost_Call{Call: _e.mock.On("OverrideCost", ctx, locale, revisionID, newCost, changedBy)}
}

func (_c *MockRevisionStore_OverrideCost_Call) Run(run func(ctx context.Context, locale string, revisionID int64, newCost int64, changedBy string)) *MockRevisionStore_OverrideCost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRevisionStore_OverrideCost_Call) Return(revision entity.Revision, err error) *MockRevisionStore_OverrideCost_Call {
	_c.Call.Return(revision, err)
	return _c
}

func (_c *MockRevisionStore_OverrideCost_Call) RunAndReturn(run func(ctx context.Context, locale string, revisionID int64, newCost int64, changedBy string) (entity.Revision, error)) *MockRevisionStore_OverrideCost_Call {
	_c.Call.Return(run)
	return _c
}
